3 stagev4
pcdshub/lcls-plc-kfe-motion pull request #98
Opened 2022-10-17 23:56 UTC by mkestra

opening this PR to indicate that I am actively working on an update for kfe-motion

2022-10-19 23:00 UTC, ghalym approved these changes

2022-10-20 00:53 UTC, ZLLentz requested changes
Can you update the PR description to reflect the changes made in the PR? It will be annoying to go back to this later and try to understand what was changed without any relevant PR text.

2022-10-20 01:00 UTC, mkestra commented
changed description to describe changes in more detail.

2022-10-20 01:03 UTC, ZLLentz commented on plc-kfe-motion/kfe_motion/POUs/PRG_RTDSK0.TcPOU
> +    IF ( bInit) THEN
This isn't important but it triggers my OCD again
```suggestion
IF bInit THEN
```

2022-10-20 01:03 UTC, ZLLentz commented on plc-kfe-motion/kfe_motion/POUs/PRG_RTDSK0.TcPOU
> +    FFO(i_xOK := NOT(Main.M13.bLimitForwardEnable) AND Main.M13.bLimitBackwardEnable, io_fbFFHWO := GVL.fbFastFaultOutput1);]]></ST>
This looks correct (zxy mapping, FFO implementation), but why is this whole block randomly indented? Why are there random spaces between the function blocks and their parentheses? Why are there extra parentheses in the middle of the i_xOK boolean? It's not wrong it's just confusing.

2022-10-20 01:04 UTC, ZLLentz approved these changes
Functionality looks good to me, pointed out some nitpicks

2022-10-20 01:12 UTC, merged